'use client';

import { Inter } from 'next/font/google'
import type {Metadata} from 'next'
import Header from '@/app/header/page'
import SideBar from '@/app/sidebar/page'
import { Provider } from 'react-redux/es/exports'
import { store } from '../store'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Slack',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
      </head>
      <body className={inter.className}>
        <Provider store={store}>
      <Header />
      <SideBar />
        {children}
        </Provider>
        </body>
    </html>
  )
}
