'use client';

import { Inter } from 'next/font/google'
import type {Metadata} from 'next'
import { Provider } from 'react-redux'
import { store } from '../rightsidebar/store'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Register',
  description: 'Generated by Arjay Onan',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider store={store}>
        {children}
        </Provider>
      </body>
    </html>
  )
}
